-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Bronze"

game:GetService("ReplicatedStorage").Communication.Functions.Respawn:InvokeServer(ohString1)

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Bronze"

game:GetService("ReplicatedStorage").Communication.Functions.Respawn:InvokeServer(ohString1)