rconsolecreate()
local Time = os.clock()

local lplr = game:GetService("Players").LocalPlayer
local usecode = game:GetService("ReplicatedStorage").Remotes.Functions.UseCode
local fall_Request = game:GetService("ReplicatedStorage").Remotes.Events.Fall_Request
local ragdoll = game:GetService("ReplicatedStorage").Remotes.Events.Ragdoll
local fall = game:GetService("ReplicatedStorage").Remotes.Events.Fall
local bleeding = game:GetService("Workspace").Characters.Players[lplr.Name].LimbHealths.bleed
local old
old = hookmetamethod(game,"__namecall",function(self,...)
    local method = getnamecallmethod()
    if self == fall and method == "FireServer" then
        return
    elseif self == fall_Request and method == "FireServer" then
        return
    elseif self == ragdoll and method == "FireServer" then
        return
    elseif self == usecode and method == "InvokeServer" then
        return
    elseif self == bleeding and method == "FireServer" then
        return
    end
    return old(self,...)
end)
rconsoleprint("Disabled fall/ragdoll/Bleeding [time taken :" .. os.clock() - Time .. "]")

game:GetService("Workspace").Doors:Destroy()
rconsoleprint("Removed all doors [time taken :" .. os.clock() - Time .. "]")

getgenv().esex = true

local Players = game:GetService('Players')
local LocalPlayer = Players.LocalPlayer

local function __hit(plr)
    if plr.Character:FindFirstChild('Head') and LocalPlayer.Character:FindFirstChildOfClass('Tool') then
        local ohInstance1 = LocalPlayer.Character:FindFirstChildOfClass('Tool')

        game:GetService("ReplicatedStorage").Remotes.Events.Swing:FireServer(ohInstance1)
        -- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide
        local ohInstance1 = LocalPlayer.Character:FindFirstChildOfClass('Tool')
        local ohInstance2 = plr.Character.Humanoid
        local ohInstance3 = plr.Character["Head"]
        local ohVector34 = plr.Character["Head"].Position
        local ohVector35 = plr.Character["Torso"].Position
        local ohCFrame6 = plr.Character["Head"].CFrame
        local ohVector37 = plr.Character["Head"].Position
        local ohNumber8 = 88.51718646302079
        local ohNil9 = nil
        local ohVector310 = plr.Character["Head"].Position

        LocalPlayer.Character:FindFirstChildOfClass('Tool').Scripts.Damage:InvokeServer(ohInstance1, ohInstance2,
            ohInstance3, ohVector34, ohVector35, ohCFrame6, ohVector37, ohNumber8, ohNil9, ohVector310)
    end
end

local function GetClosest()
    local Character = LocalPlayer.Character
    local HumanoidRootPart = Character and Character:FindFirstChild("HumanoidRootPart")
    if not (Character or HumanoidRootPart) then
        return
    end

    local TargetDistance = tonumber(55)
    local Target

    for i, v in ipairs(Players:GetPlayers()) do
        if v ~= LocalPlayer and v.Character and v.Character:FindFirstChild("HumanoidRootPart") and
            v.Character:FindFirstChild("Humanoid") and LocalPlayer.Character:FindFirstChild("HumanoidRootPart") and
            v.Character:FindFirstChild("Humanoid").Health > 0 and v.Character:FindFirstChild("Highlight") == nil then
            local TargetHRP = v.Character.HumanoidRootPart
            local mag = (HumanoidRootPart.Position - TargetHRP.Position).magnitude
            if mag < TargetDistance then
                TargetDistance = mag
                Target = v
            end
        elseif v.Character then
            if v.Character:FindFirstChild("Highlight") ~= nil then
                if Target ~= v then
                    v.Character:FindFirstChild("Highlight"):Destroy()
                end
            end
        end
    end

    return Target
end

coroutine.wrap(function()
    local self = game:GetService('RunService').RenderStepped:Connect(function()
        if getgenv().esex then
            if GetClosest() then
                __hit(GetClosest())
            end
        else
            return
        end
    end)
end)()